### ISSUE TITLE
Change the heading color in blogs page

### ISSUE THREAD

**Issue by garvitgupta13** [ProjectSakura/ProjectSakura.github.io#164]
Currently, the heading is almost not visible on the blogs page.
Should change the colour of heading to white to make it readable
![image](https://user-images.githubusercontent.com/70805691/111379349-0a0b6700-86c9-11eb-8b7d-c304b747b6ec.png)

**Comment by garvitgupta13** [comment]
Please assign it to me under gssoc21

**Comment by ArunTeltia** [comment]
I guess someone had done something wrong @LordShenron have a look at it, 
For now this is absolute valid issue and It must have high priority to be resolved, 
@garvitgupta13 If you want this issue I can give it to you but please word on this fast, otherwise i need to work on this 

I am assigning this issue to you

**Comment by LordShenron** [comment]
> I guess someone had done something wrong @LordShenron have a look at it,
> For now this is absolute valid issue and It must have high priority to be resolved,
> @garvitgupta13 If you want this issue I can give it to you but please word on this fast, otherwise i need to work on this
> 
> I am assigning this issue to you

Oopsies happen all the time
